### ISSUE TITLE
建议作者给个例子，我看了下，你只是告诉了我们步骤该怎么做，没有实际的例子

### ISSUE THREAD

**Issue by wangjingwj** [yanthink/react-simplemde-editor#2]
我觉得给个例子，git clone之后，然后安装以来，然后能跑的起来，这样看这个能不能满足我们的需求

**Comment by wangjingwj** [comment]
还有我看了src源代码下的theme文件好像没用到

**Comment by wangjingwj** [comment]
还有如何方便的话，可以留个微信或者扣扣，如果遇到问题话可以请教下，多谢啦

**Comment by yanthink** [comment]
> 我觉得给个例子，git clone之后，然后安装以来，然后能跑的起来，这样看这个能不能满足我们的需求

源码里有demo哦，你可以clone下来运行demo看看效果

**Comment by wangjingwj** [comment]
我已经clone下来了，但是我需要在你的基础上做些修改，我们的需求和你的这个还有点差距，如何您方便的话，能否加下我的扣扣（2411248492）或者微信(15951677168)，因为在github上面不一定及时看到，我之前对这个也没有用过，属于边学边做的状态，后期我如果有问题的话想请教下，多谢啦🙏

**Comment by wangjingwj** [comment]
> > 我觉得给个例子，git clone之后，然后安装以来，然后能跑的起来，这样看这个能不能满足我们的需求
> 
> 源码里有demo哦，你可以clone下来运行demo看看效果

参照你demo里面的例子，粘贴的也不行，应该是你上传的地址报404
