### ISSUE TITLE
Replace Chinese into EmojiPicker

### ISSUE THREAD

**Issue by Gus19** [yanthink/react-simplemde-editor#5]
Hello,

I found your plugin and I love it :smiley:

But I search to replace the Chinese into the EmojiPicker and I don't find how to do that.
Could you help me ?

Thanks !

**Comment by yanthink** [comment]
https://github.com/yanthink/react-simplemde-editor#emoji 最新版本支持 categories 自定义

**Comment by Gus19** [comment]
Thanks a lot :+1:
